# Generated by Django 6.0.4 on 2026-04-18 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_dreamreal_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='contact',
            new_name='econtact',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='empno',
            new_name='eid',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='empname',
            new_name='ename',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='joined_date',
        ),
    ]
